### ISSUE TITLE
[FEATURE] Provide auto configuration for AWS transport

### ISSUE THREAD

**Issue by hberrayana** [opensearch-project/spring-data-opensearch#267]
### Is your feature request related to a problem?

The current opensearch auto configuration doesn't allow auto-creating clients that use the AwsSdk2Transport. 
I'd like to be able to configure my application locally to connect to docker OS instance and use aws opensearch service for the non-local environments.

This change should be possible using predefined properties such as 

```yaml
cloud:
 aws:
   credentials:
     access-key: KEY
     secret-key: SECRET
   region:
     static: us-west-2
     auto: false
opensearch:
  aws-endpoint: search-...us-west-2.es.amazonaws.com
```

On a local environment I should be able to connect to a local O.S cluster without changing my code through a simple configuration:

```yaml
opensearch:
  uris: https://localhost:9200
  username: admin
  password: admin
 
```

### What solution would you like?

The auto configuration should be able to build a proper `OpenSearchClient` instance dependent on the provided configuration parameters.

### What alternatives have you considered?

Creating two `@Configuration` classes but there's a better way to do it.

### Do you have any additional context?

The class [OpenSearchProperties.java](https://github.com/opensearch-project/spring-data-opensearch/blob/main/spring-data-opensearch-starter/src/main/java/org/opensearch/spring/boot/autoconfigure/OpenSearchProperties.java) does not contain any parameter that allows to specify an aws configuration.

The java client documentation provides a guide to connect to opensearch aws service

SdkHttpClient httpClient = ApacheHttpClient.builder().build();

```java
OpenSearchClient client = new OpenSearchClient(
    new AwsSdk2Transport(
        httpClient,
        "search-...us-west-2.es.amazonaws.com", // OpenSearch endpoint, without https://
        "es",
        Region.US_WEST_2, // signing service region
        AwsSdk2TransportOptions.builder().build()
    )
);
```
